exports.RELATIONSHIP_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
  UNFRIEND: 'UNFRIEND'
};

exports.RELATIONSHIP_TO_AUTH_USER = {
  ME: 'ME',
  UNKNOWN: 'UNKNOWN',
  FRIEND: 'FRIEND',
  SENDER: 'SENDER',
  RECEIVER: 'RECEIVER'
};
